### PR TITLE
3.0.0 release

### PR DESCRIPTION
**Pull request by dichiarafrancesco**

### CODE REVIEW

**Comment by venkey-ariv** [comment]
+1

**Review by smoy — APPROVED** [review]
<3 go go go

**Comment by n-my** [comment]
Great! Any future plan to make the jar available on Maven central repository ?

**Comment by dichiarafrancesco** [comment]
hi @n-my were thinking to do that. Feel free to open an issue though 👍

**Comment by n-my** [comment]
hi @dichiarafrancesco 
It doesn't look your fork is setup to accept issues ?

**Comment by dichiarafrancesco** [comment]
hi @n-my I think you can now open issues! we just enabled the feature :)

**Pull request merged**
